#!/usr/bin/env php
<?php
/**
 * If you want to run tests, you must install PHPUnit library (http://www.phpunit.de/)
 * in the lib directory.
 * Then you must copy db-credentials-example.ini to db-credentials.ini and correct DSNs.
 * Then you may execute something like:
 * $ test/run test/DB/Adapter/Generic/DBTest.php
 */

error_reporting(E_ALL);
ini_set('display_errors','On');
ini_set('include_path', '.');

require_once 'TestConfig.php';
TestConfig::$dsn = parse_ini_file(dirname(__FILE__) . '/db-credentials.ini');
require_once dirname(__FILE__) . '/../lib/config.php';

if (extension_loaded('xdebug')) {
    ini_set('xdebug.show_exception_trace', 0);
}

require_once 'PHPUnit/Util/Filter.php';
PHPUnit_Util_Filter::addFileToFilter(__FILE__, 'PHPUNIT');

require 'PHPUnit/TextUI/Command.php';
define('PHPUnit_MAIN_METHOD', 'PHPUnit_TextUI_Command::main');
PHPUnit_TextUI_Command::main();
