#!/usr/bin/env php
<?php
/**
 * If you want to run tests, you must install PHPUnit library (http://www.phpunit.de/)
 * in the lib directory.
 * Then you must copy db-credentials-example.ini to db-credentials.ini and correct DSNs.
 * Then you may execute something like:
 * $ test/run test/DB/Adapter/Generic/DBTest.php
 */

error_reporting(E_ALL);
ini_set('display_errors','On');
set_include_path(dirname(__FILE__) . PATH_SEPARATOR . get_include_path());
set_include_path(dirname(dirname(__FILE__)) . PATH_SEPARATOR . get_include_path());

require_once 'TestConfig.php';
require_once dirname(__FILE__) . '/../lib/config.php';
require_once 'PHPUnit/Util/Filter.php';
require 'PHPUnit/TextUI/Command.php';

TestConfig::$dsn = parse_ini_file(dirname(__FILE__) . '/db-credentials.ini');
PHPUnit_Util_Filter::addFileToFilter(__FILE__, 'PHPUNIT');
define('PHPUnit_MAIN_METHOD', 'PHPUnit_TextUI_Command::main');
PHPUnit_TextUI_Command::main();
